version = "1.0"

[main]
name.en = "Wanderer configuration"
name.fr = "Configuration de Wanderer"
services = [ "__APP__-search", "__APP__-db", "__APP__-web" ]

    [main.config]
    name.en = "Configuration options"
    name.fr = "Options de configuration"

        [main.config.disable_signup]
        ask.en = "Disabling registration?"
        ask.fr = "Désactivation de l'enregistrement ?"
        type = "boolean"
        yes = "true"
        no = "false"
        bind = "PUBLIC_DISABLE_SIGNUP:__INSTALL_DIR__/.env"
