#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.89beb4b.name = "0.12.0~ynh1"
    test_upgrade_from.4d9cdae.name = "0.15.2"
    test_upgrade_from.5d42579.name = "0.16.5"
