#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
## SET STANDARD SETTINGS FROM MANIFEST
#=================================================

ynh_script_progression --message="Storing installation settings..." --weight=1

disable_signup="false"
ynh_app_setting_set --key=disable_signup --value="$disable_signup"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="main"
ynh_setup_source --dest_dir="$install_dir/search" --source_id="meili"

chmod +x "$install_dir/search/meilisearch"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=key --value=$key

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template="meili-config.toml" --destination="$install_dir/search/config.toml"


# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate
touch /var/log/$app/$app.log
touch /var/log/$app/$app-search.log
touch /var/log/$app/$app-db.log

chown -R $app:$app /var/log/$app/

#=================================================
# BUILDING SOURCES AND SETTING UP THE SERVER
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings ynh_go_install

ynh_script_progression "Building the search engine..."
pushd "$install_dir/search"
    export MEILI_MASTER_KEY=$key
    export MEILI_NO_ANALYTICS=true
    ynh_hide_warnings "$install_dir"/search/meilisearch --config-file-path="$install_dir/search/config.toml" --import-dump migrations/migration.dump > "/var/log/$app/$app.log" 2>&1 &
popd

ynh_script_progression "Building the database (it will take some time)..."
pushd "$install_dir/db"
	export GOPATH="$install_dir/build/go"
	export GOCACHE="$install_dir/build/.cache"
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=1 go mod tidy 
	ynh_hide_warnings go build
popd

ynh_go_remove
ynh_safe_rm "$install_dir/build"
ynh_safe_rm "$install_dir/.cache"

ynh_script_progression "Building the web (it will take some time)..."
pushd "$install_dir/web"
	ynh_hide_warnings ynh_exec_as_app npm ci
    ynh_hide_warnings ynh_exec_as_app PUBLIC_VALHALLA_URL=https://valhalla1.openstreetmap.de npm run build
	ynh_hide_warnings ynh_exec_as_app npm cache clean --force
popd

chown -R $app:$app "$install_dir/"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}-search" --template="wanderer-search.service"
ynh_config_add_systemd --service="${app}-db" --template="wanderer-db.service"
ynh_config_add_systemd --service="${app}-web" --template="wanderer-web.service"

yunohost service add "${app}-search" --description="Wanderer search service" --log="/var/log/$app/$app-search.log"
yunohost service add "${app}-db" --description="Wanderer PocketBase service" --log="/var/log/$app/$app-db.log"
yunohost service add "${app}-web" --description="Wanderer web service" --log="/var/log/$app/$app.log"

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"



#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="${app}-search" --action="start"
ynh_systemctl --service="${app}-db" --action="start"
ynh_systemctl --service="${app}-web" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
