#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

key=$(ynh_string_random --length=45 | base64)

ynh_app_setting_set --key=key --value=$key

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# BUILDING SOURCES AND SETTING UP THE SERVER
#=================================================
ynh_script_progression --message="Building the sources (it will take some time)..."

ynh_hide_warnings ynh_go_install

pushd "$install_dir/search"
    export MEILI_MASTER_KEY=$key
    export MEILI_NO_ANALYTICS=true
    ynh_hide_warnings /var/www/meilisearch/meilisearch --import-dump migrations/migration.dump
popd

pushd "$install_dir/db"
    go mod tidy && go build
popd

ynh_go_remove

pushd "$install_dir/web"
	ynh_hide_warnings ynh_exec_as_app npm ci --omit=dev
        ynh_hide_warnings ynh_exec_as_app npm run build
	ynh_hide_warnings ynh_exec_as_app npm cache clean --force
popd


#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}-search" --template="wanderer-search.service"
ynh_config_add_systemd --service="${app}-db" --template="wanderer-db.service"
ynh_config_add_systemd --service="${app}-web" --template="wanderer-web.service"

yunohost service add "${app}-search" --description="Wanderer search service" --log="/var/log/$app/$app.log"
yunohost service add "${app}-db" --description="Wanderer PocketBase service" --log="/var/log/$app/$app.log"
yunohost service add "${app}-web" --description="Wanderer web service" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
