#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# ynh_config_remove_fail2ban

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status "${app}-search" >/dev/null
then
	ynh_script_progression "Removing "${app}-search" service integration..."
	yunohost service remove "${app}-search"
fi

if ynh_hide_warnings yunohost service status "${app}-db" >/dev/null
then
	ynh_script_progression "Removing "${app}-db" service integration..."
	yunohost service remove "${app}-db"
fi

if ynh_hide_warnings yunohost service status "${app}-web" >/dev/null
then
	ynh_script_progression "Removing "${app}-web" service integration..."
	yunohost service remove "${app}-web"
fi

ynh_config_remove_systemd "${app}-search"
ynh_config_remove_systemd "${app}-db"
ynh_config_remove_systemd "${app}-web"

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
