#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/"${app}-search".service"
ynh_restore "/etc/systemd/system/"${app}-db".service"
ynh_restore "/etc/systemd/system/"${app}-web".service"

systemctl enable ""${app}-search"" --quiet
systemctl enable ""${app}-db"" --quiet
systemctl enable ""${app}-web"" --quiet

yunohost service add "${app}-search" --description="Wanderer search service" --log="/var/log/$app/$app-search.log"
yunohost service add "${app}-db" --description="Wanderer PocketBase service" --log="/var/log/$app/$app-db.log"
yunohost service add "${app}-web" --description="Wanderer web service" --log="/var/log/$app/$app-web.log"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="${app}-search" --action="start"
ynh_systemctl --service="${app}-db" --action="start"
ynh_systemctl --service="${app}-web" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
