#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

ynh_app_setting_set_default --key=disable_signup --value=false


if ynh_app_upgrading_from_version_before 0.16.4~ynh3
then
encrypt_key=$(ynh_string_random --length=32)
ynh_app_setting_set --key=encrypt_key --value=$encrypt_key
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="${app}-search" --action="stop"
ynh_systemctl --service="${app}-db" --action="stop"
ynh_systemctl --service="${app}-web" --action="stop"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

#ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --source_id="main" --keep="db/pb_data search/data.ms"
ynh_setup_source --dest_dir="$install_dir/search" --source_id="meili"

chmod +x "$install_dir/search/meilisearch"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# BUILDING SOURCES AND SETTING UP THE SERVER
#=================================================
ynh_script_progression "Installing dependencies..."

$ynh_hide_warnings ynh_go_install

ynh_script_progression "Upgrading meilisearch database"
pushd "$install_dir/search"
	export MEILI_URL=http://127.0.0.1:$port_meili
	export MEILI_MASTER_KEY=$key
	export MEILI_NO_ANALYTICS=true
    "$install_dir"/search/meilisearch --experimental-dumpless-upgrade > "/var/log/$app/$app-search.log" 2>&1 &
popd

# Wait for the specific log message to appear
ynh_script_progression "Waiting for Meilisearch to finish importing..."
while ! grep -q "Actix runtime found; starting in Actix" "/var/log/$app/$app-search.log"; do
    sleep 2 # Sleep for 2 seconds before checking the log file again
done

# Terminate Meilisearch process using pkill
pkill -f "$install_dir/search/meilisearch"


ynh_script_progression "Building the database (it will take some time)..."
pushd "$install_dir/db"
	export MEILI_URL=http://127.0.0.1:$port_meili
	export MEILI_MASTER_KEY=$key
	export MEILI_NO_ANALYTICS=true
	export PUBLIC_POCKETBASE_URL=http://127.0.0.1:$port_pocketbase
	export NODE_ENV=production

	export GOPATH="$install_dir/build/go"
	export GOCACHE="$install_dir/build/.cache"
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=1 go mod tidy 
	ynh_hide_warnings go build
popd

ynh_go_remove
ynh_safe_rm "$install_dir/build"
ynh_safe_rm "$install_dir/.cache"

ynh_script_progression "Building the Web (it will take some time)..."
pushd "$install_dir/web"
	export MEILI_URL=http://127.0.0.1:$port_meili
	export MEILI_MASTER_KEY=$key
	export MEILI_NO_ANALYTICS=true
	export PUBLIC_POCKETBASE_URL=http://127.0.0.1:$port_pocketbase
	
	export NODE_ENV=production
	export CYPRESS_INSTALL_BINARY=0
	
	ram_G=$((($(ynh_get_ram --total) - (1024/2))/1024))
	ram_G=$(($ram_G > 1 ? $ram_G : 1))
	export NODE_OPTIONS="--max_old_space_size=$(($ram_G*1024))"

	ynh_hide_warnings ynh_exec_as_app npm install vite
	ynh_hide_warnings ynh_exec_as_app npm ci --include=dev
	ynh_hide_warnings ynh_exec_as_app PUBLIC_VALHALLA_URL=https://valhalla1.openstreetmap.de npm run build
	ynh_hide_warnings ynh_exec_as_app npm ci --omit=dev
	ynh_hide_warnings ynh_exec_as_app npm cache clean --force
	ynh_hide_warnings ynh_exec_as_app npm prune --production
popd

chown -R $app:$app "$install_dir/"

#Remove unneeded files
ynh_safe_rm "$install_dir"/go
ynh_safe_rm "$install_dir"/web/.svelte-kit/
ynh_safe_rm "$install_dir"/web/tests
ynh_safe_rm "$install_dir"/docs
ynh_safe_rm "$install_dir"/.npm
ynh_safe_rm "$install_dir"/.github
ynh_safe_rm "$install_dir"/.config

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}-search" --template="wanderer-search.service"
ynh_config_add_systemd --service="${app}-db" --template="wanderer-db.service"
ynh_config_add_systemd --service="${app}-web" --template="wanderer-web.service"

yunohost service add "${app}-search" --description="Wanderer search service" --log="/var/log/$app/$app-search.log"
yunohost service add "${app}-db" --description="Wanderer PocketBase service" --log="/var/log/$app/$app-db.log"
yunohost service add "${app}-web" --description="Wanderer Web service" --log="/var/log/$app/$app-web.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="${app}-search" --action="start"
ynh_systemctl --service="${app}-db" --action="start"
ynh_systemctl --service="${app}-web" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
