#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

ynh_app_setting_set_default --key=disable_signup --value=false

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="${app}-search" --action="stop"
ynh_systemctl --service="${app}-db" --action="stop"
ynh_systemctl --service="${app}-web" --action="stop"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --source_id="main" --keep="database"
ynh_setup_source --dest_dir="$install_dir/search" --full_replace --source_id="meili"

chmod +x "$install_dir/search/meilisearch"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template="meili-config.toml" --destination="$install_dir/search/config.toml"

#=================================================
# BUILDING SOURCES AND SETTING UP THE SERVER
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings ynh_go_install

ynh_script_progression "Building the database (it will take some time)..."
pushd "$install_dir/db"
	export GOPATH="$install_dir/build/go"
	export GOCACHE="$install_dir/build/.cache"
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=1 go mod tidy 
	ynh_hide_warnings go build
popd

ynh_go_remove

ynh_script_progression "Building the web (it will take some time)..."
pushd "$install_dir/web"
	ynh_hide_warnings ynh_exec_as_app npm ci
    ynh_hide_warnings ynh_exec_as_app PUBLIC_VALHALLA_URL=https://valhalla1.openstreetmap.de npm run build
	ynh_hide_warnings ynh_exec_as_app npm cache clean --force
popd

chown -R $app:$app "$install_dir/"


#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}-search" --template="wanderer-search.service"
ynh_config_add_systemd --service="${app}-db" --template="wanderer-db.service"
ynh_config_add_systemd --service="${app}-web" --template="wanderer-web.service"

yunohost service add "${app}-search" --description="Wanderer search service" --log="/var/log/$app/$app-search.log"
yunohost service add "${app}-db" --description="Wanderer PocketBase service" --log="/var/log/$app/$app-db.log"
yunohost service add "${app}-web" --description="Wanderer web service" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
